version: "2"
services:


  nginx:
    restart: always
    container_name: dev-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./.docker/nginx_machine/certs:/etc/nginx/certs:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - hive


  nginx-gen:
    restart: always
    container_name: dev-nginx-gen
    image: jwilder/docker-gen
    volumes_from:
      - nginx
    volumes:
      - "./.docker/nginx_machine/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx


  nginx-letsencrypt:
    restart: always
    container_name: dev-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "./.docker/nginx_machine/certs:/etc/nginx/certs:rw"
      - "./.docker/nginx_machine/vhost.d:/etc/nginx/vhost.d:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - nginx
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=dev-nginx-gen
    depends_on:
      - nginx
      - nginx-gen


  dev:
    restart: always
    container_name: dev-ubuntu
    image: dev-ubuntu-image
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: .docker/ubuntu.dev.dockerfile
    networks:
      - hive
    ports:
      - "9000:9000"
      - "49154:22"
    volumes:
      - ./services/web:/root/devproject/web
      - /root/devproject/web/node_modules
      - ./services/app:/root/devproject/app
      - /root/devproject/app/node_modules
      - ./services/cms:/root/devproject/cms
      - /root/devproject/cms/node_modules
      - ./services/api:/root/devproject/api
      - /root/devproject/api/node_modules
    working_dir: /root/devproject
    depends_on:
      - site
      - web
      - app
      - cms


  web:
    restart: always
    container_name: dev-web
    image: dev-web-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=web
    env_file:
      - ./.docker/node_machine/node.dev.env
    environment:
      - VIRTUAL_HOST=web.domusnetwork.io
      - VIRTUAL_NETWORK=domusnetwork
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=web.domusnetwork.io
      - LETSENCRYPT_EMAIL=admin@domusnetwork.io
    networks:
      - hive
    ports:
      - "8080:8080"
    volumes:
      - ./services/web:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:      
      - api


  app:
    restart: always
    container_name: dev-app
    image: dev-app-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=app
    env_file:
      - ./.docker/node_machine/node.dev.env
    environment:
      - VIRTUAL_HOST=app.domusnetwork.io
      - VIRTUAL_NETWORK=domusnetwork
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=app.domusnetwork.io
      - LETSENCRYPT_EMAIL=admin@domusnetwork.io
    networks:
      - hive
    ports:
      - "3000:3000"
    volumes:
      - ./services/app:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:      
      - api


  cms:
    restart: always
    container_name: dev-cms
    image: dev-cms-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=cms
    env_file:
      - ./.docker/node_machine/node.dev.env
    environment:
      - VIRTUAL_HOST=cms.domusnetwork.io
      - VIRTUAL_NETWORK=domusnetwork
      - VIRTUAL_PORT=7000
      - LETSENCRYPT_HOST=cms.domusnetwork.io
      - LETSENCRYPT_EMAIL=admin@domusnetwork.io
    networks:
      - hive
    ports:
      - "7000:7000"
    volumes:
      - ./services/cms:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:
      - api


  api:
    restart: always
    container_name: dev-api
    image: dev-api-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=api
    env_file:
      - ./.docker/node_machine/node.dev.env
    environment:
      - VIRTUAL_HOST=api.domusnetwork.io
      - VIRTUAL_NETWORK=domusnetwork
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.domusnetwork.io
      - LETSENCRYPT_EMAIL=admin@domusnetwork.io
    networks:
      - hive
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:
      - nginx
      - nginx-gen
      - nginx-letsencrypt
      - mongo


  mongo:
    restart: always
    container_name: dev-mongo
    image: dev-mongo-image
    build:
      context: .
      dockerfile: ./.docker/mongo.dev.dockerfile
    env_file:
      - ./.docker/mongo_machine/mongo.dev.env
    volumes:
      - database_data:/var/lib/mongo
    networks:
      - hive
    ports:
      - "27017"



volumes:
    database_data:
        driver: local



networks:
  hive:
    external:
      name: domusnetwork
