version: "2"
services:


  dev:
    restart: always
    container_name: dev-ubuntu
    image: dev-ubuntu-image
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: .docker/ubuntu.dev.dockerfile
    networks:
      - hive
    ports:
      - "9000:9000"
      - "49154:22"
    volumes:
      - ./services/web:/root/devproject/web
      - /root/devproject/web/node_modules
      - ./services/app:/root/devproject/app
      - /root/devproject/app/node_modules
      - ./services/cms:/root/devproject/cms
      - /root/devproject/cms/node_modules
      - ./services/api:/root/devproject/api
      - /root/devproject/api/node_modules
    working_dir: /root/devproject
    depends_on:
      - web
      - app
      - cms


  web:
    restart: always
    container_name: dev-web
    image: dev-web-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=web
    env_file:
      - ./.docker/node_machine/node.dev.env
    networks:
      - hive
    ports:
      - "8080:8080"
    volumes:
      - ./services/web:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:      
      - api


  app:
    restart: always
    container_name: dev-app
    image: dev-app-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=app
    env_file:
      - ./.docker/node_machine/node.dev.env
    networks:
      - hive
    ports:
      - "3000:3000"
    volumes:
      - ./services/app:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:      
      - api


  cms:
    restart: always
    container_name: dev-cms
    image: dev-cms-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=cms
    env_file:
      - ./.docker/node_machine/node.dev.env
    networks:
      - hive
    ports:
      - "7000:7000"
    volumes:
      - ./services/cms:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:
      - api


  api:
    restart: always
    container_name: dev-api
    image: dev-api-image
    command: npm start
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
      args:
        - name=api
    env_file:
      - ./.docker/node_machine/node.dev.env
    networks:
      - hive
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/root/service
      - /root/service/node_modules
    working_dir: /root/service
    depends_on:
      - mongo


  mongo:
    restart: always
    container_name: dev-mongo
    image: dev-mongo-image
    build:
      context: .
      dockerfile: ./.docker/mongo.dev.dockerfile
    env_file:
      - ./.docker/mongo_machine/mongo.dev.env
    volumes:
      - database_data:/var/lib/mongo
    networks:
      - hive
    ports:
      - "27017"



volumes:
    database_data:
        driver: local



networks:
  hive:
    external:
      name: domusnetwork
